### ISSUE TITLE
ONE_TIME_ADDRESS is not defined

### ISSUE THREAD

**Issue by vokracko** [fireblocks/fireblocks-sdk-py#19]
```python
>>> from fireblocks_sdk import ONE_TIME_ADDRESS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lv/Downloads/fireblocks-sdk-py/fireblocks_sdk/__init__.py", line 1, in <module>
    from fireblocks_sdk.sdk import FireblocksSDK
  File "/home/lv/Downloads/fireblocks-sdk-py/fireblocks_sdk/sdk.py", line 6, in <module>
    from .api_types import FireblocksApiException, TRANSACTION_TYPES, TRANSACTION_STATUS_TYPES, PEER_TYPES, TransferPeerPath, DestinationTransferPeerPath, TransferTicketTerm, TRANSACTION_TRANSFER, SIGNING_ALGORITHM, UnsignedMessage, FEE_LEVEL
  File "/home/lv/Downloads/fireblocks-sdk-py/fireblocks_sdk/api_types.py", line 39, in <module>
    TRANSACTION_TYPES = (TRANSACTION_TRANSFER, TRANSACTION_MINT, TRANSACTION_BURN, TRANSACTION_SUPPLY_TO_COMPOUND, TRANSACTION_REDEEM_FROM_COMPOUND, RAW, CONTRACT_CALL, ONE_TIME_ADDRESS)
NameError: name 'ONE_TIME_ADDRESS' is not defined
```

**Comment by vokracko** [comment]
Fix in https://github.com/fireblocks/fireblocks-sdk-py/pull/20
