### ISSUE TITLE
Bug introduced in 1.6.3 with `treat_as_gross_amount`

### ISSUE THREAD

**Issue by shuckc** [fireblocks/fireblocks-sdk-py#45]
Release 1.6.3 in 7e3d66c  you've removed `treat_as_gross_amount` from the arguments list, but not from the body preparation, so `create_transaction` does not work:

```
Traceback (most recent call last):
  File "/xxx/enricher.py", line 1147, in post
    tx_result = self.fireblocks.create_transaction(**kwargs)
  File "/xxx/venv/lib/python3.9/site-packages/fireblocks_sdk/sdk.py", line 720, in create_transaction
    if treat_as_gross_amount:
NameError: name 'treat_as_gross_amount' is not defined
```

**Comment by yarinvak** [comment]
fixed in 1.6.4 thanks for reporting
